#!/usr/bin/env bash
# harness-audit HTML report generator
# Usage: generate-report.sh <results.json> <output.html>
#   results.json: [{"id":1,"name":"...","exit_code":0,"action":"..."},...]
set -euo pipefail

RESULTS="${1:?Usage: generate-report.sh <results.json> <output.html>}"
OUTPUT="${2:?Missing output path}"
PROJECT_DIR="$(pwd)"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"

TOTAL=$(jq 'length' "$RESULTS")
PASSED=$(jq '[.[] | select(.exit_code == 0)] | length' "$RESULTS")
FAILED=$((TOTAL - PASSED))

if [ "$FAILED" -eq 0 ]; then
  HEALTH="Healthy"
  HEALTH_COLOR="#22c55e"
  HEALTH_BG="#f0fdf4"
elif [ "$FAILED" -le 2 ]; then
  HEALTH="Needs Attention"
  HEALTH_COLOR="#f59e0b"
  HEALTH_BG="#fffbeb"
else
  HEALTH="Critical"
  HEALTH_COLOR="#ef4444"
  HEALTH_BG="#fef2f2"
fi

ROWS=""
while IFS= read -r row; do
  id=$(echo "$row" | jq -r '.id')
  name=$(echo "$row" | jq -r '.name')
  exit_code=$(echo "$row" | jq -r '.exit_code')
  action=$(echo "$row" | jq -r '.action // "-"')

  if [ "$exit_code" -eq 0 ]; then
    badge='<span style="background:#dcfce7;color:#166534;padding:2px 10px;border-radius:12px;font-weight:600;font-size:13px">PASS</span>'
  else
    badge='<span style="background:#fecaca;color:#991b1b;padding:2px 10px;border-radius:12px;font-weight:600;font-size:13px">FAIL</span>'
  fi

  ROWS="${ROWS}<tr>
    <td style='padding:12px 16px;border-bottom:1px solid #e5e7eb;text-align:center;color:#6b7280'>${id}</td>
    <td style='padding:12px 16px;border-bottom:1px solid #e5e7eb;font-weight:500'>${name}</td>
    <td style='padding:12px 16px;border-bottom:1px solid #e5e7eb;text-align:center'>${badge}</td>
    <td style='padding:12px 16px;border-bottom:1px solid #e5e7eb;color:#6b7280;font-size:13px'>${action}</td>
  </tr>"
done < <(jq -c '.[]' "$RESULTS")

cat > "$OUTPUT" <<HTMLEOF
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Harness Audit Report</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; background:#f8fafc; color:#1e293b; padding:32px; }
  .container { max-width:800px; margin:0 auto; }
  .header { margin-bottom:32px; }
  .header h1 { font-size:24px; font-weight:700; margin-bottom:4px; }
  .header p { color:#64748b; font-size:14px; }
  .cards { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-bottom:32px; }
  .card { background:#fff; border:1px solid #e2e8f0; border-radius:12px; padding:20px; }
  .card .label { font-size:12px; color:#94a3b8; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:4px; }
  .card .value { font-size:28px; font-weight:700; }
  .card .sub { font-size:12px; color:#94a3b8; margin-top:2px; }
  table { width:100%; background:#fff; border:1px solid #e2e8f0; border-radius:12px; border-spacing:0; overflow:hidden; }
  th { padding:12px 16px; text-align:left; font-size:12px; color:#64748b; text-transform:uppercase; letter-spacing:0.05em; background:#f8fafc; border-bottom:2px solid #e2e8f0; }
  .footer { margin-top:24px; text-align:center; color:#94a3b8; font-size:12px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Harness Engineering Audit</h1>
    <p>${PROJECT_DIR} &mdash; ${TIMESTAMP}</p>
  </div>
  <div class="cards">
    <div class="card">
      <div class="label">Health</div>
      <div class="value" style="color:${HEALTH_COLOR}">${HEALTH}</div>
      <div class="sub">${PASSED}/${TOTAL} checks passed</div>
    </div>
    <div class="card">
      <div class="label">Passed</div>
      <div class="value" style="color:#22c55e">${PASSED}</div>
      <div class="sub">exit code 0</div>
    </div>
    <div class="card">
      <div class="label">Failed</div>
      <div class="value" style="color:${FAILED:+#ef4444}${FAILED:+}">${FAILED}</div>
      <div class="sub">action required</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th style="text-align:center;width:40px">#</th>
        <th>Check</th>
        <th style="text-align:center;width:80px">Result</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      ${ROWS}
    </tbody>
  </table>
  <div class="footer">
    Generated by harness-audit &mdash; deterministic shell-based checks
  </div>
</div>
</body>
</html>
HTMLEOF

echo "Report generated: ${OUTPUT}"
